### ISSUE TITLE
How to Implement this in VueJS project?

### ISSUE THREAD

**Issue by mcnaveen** [lotrekagency/vue-dark-mode-switcher#1]
I pasted these line in main.js

![image](https://user-images.githubusercontent.com/8493007/79013707-eec5dc80-7b86-11ea-9c05-5c73c6a4f3e8.png)

And Under App.vue 
![image](https://user-images.githubusercontent.com/8493007/79013783-1026c880-7b87-11ea-80c6-15c400b69f01.png)

And Added this in Index.html <style> tag

`
.theme-dark{
    background: black;
    color: white;
}
`

This is What I'm seeing in Browser
![image](https://user-images.githubusercontent.com/8493007/79013833-30ef1e00-7b87-11ea-90b8-9a5119babee5.png)

I'm Complete newbie to this stuff. Guide me please.

**Comment by mino89** [comment]
is the class="theme-dark"

**Comment by mino89** [comment]
```
Vue.component('yourcomponentName', {
  components: {DarkMode}
  template:'<DarkMode></DarkMode>' <- remove this line
}
```

**Comment by the-mcnaveen** [comment]
I don't have live project bro. I'm running in localhost.

I removed that line as you said. Here is what console says.

![image](https://user-images.githubusercontent.com/8493007/79677797-950e8380-8212-11ea-9a01-12ee01957ed0.png)

**Comment by mino89** [comment]
can you paste the code on you app.vue?
